### ISSUE TITLE
Run "succeeded" even if I chose the wrong data residency option

### ISSUE THREAD

**Issue by dasilvacontin** [ak--47/sheets-mixpanel#10]
While recording a Loom, I realised that I was choosing the data residency incorrectly (misled by the Timezone field in the project settings).

Using the right project region made it work.

It was not helpful that when I chose the wrong data residency option it would still succeed. I've probably lost 1h of time, if not more, due to this.

Ideally it would fail. Ideally the code can figure out the data residency itself, rather than having to provide it.

Thank you for your effort in helping, wish you a great weekend!

**Comment by ak--47** [comment]
understood. sorry for the trouble. thanks!
