### ISSUE TITLE
Multiple tabs on one google sheet - Sync issue

### ISSUE THREAD

**Issue by MariaRazzak** [ak--47/sheets-mixpanel#12]
Mixpanel > Sheet Issue :
I have multiple reports synced to a google sheet, that show as different tabs in the sheet. However, none of them sync on their own after every hour. I need to go to extension> Sync now, and do it manually --- even that results in just one sheet/report syncing, not the others. What's the issue here? Is it because one sheet can have only one report synced? Or can multiple be added to one? (Screenshot attached for reference)
<img width="786" alt="mp_issue" src="https://github.com/mixpanel/sheets/assets/136692277/0dae9293-86b2-46ea-8b78-564a95126343">

**Comment by ak--47** [comment]
hi @MariaRazzak currently, multiple reports within the same sheet is not supported. 

for subsequent releases, we are looking at supporting a single board, which would allow you to export multiple reports in the same sheet(using different tabs)...

closing for now, and will mention this issue in the next release.
