### ISSUE TITLE
402 error when run 'mixpanel -> sheet'

### ISSUE THREAD

**Issue by MrCoder** [ak--47/sheets-mixpanel#13]
Hi team, please see the below screenshot. I have got a 402 error every time I click 'run' or 'sync'. The service account is correct. I have validated them with postman. Could you please help?

<img width="651" alt="Screenshot 2023-07-08 at 7 37 31 pm" src="https://github.com/mixpanel/sheets/assets/169417/9d008454-160a-4322-83a2-4904a33c08b5">

**Comment by JakeWymer** [comment]
Hey @MrCoder, sorry about the confusing error message here. It looks like this is happening because the sheets extension uses the `Formatted API export` feature in Mixpanel, which is currently not available our free plan. Again, apologies for the confusion!
