### ISSUE TITLE
Fail to update existing Lookup table

### ISSUE THREAD

**Issue by dorothy-koh** [ak--47/sheets-mixpanel#15]
Hey there, 

there seems to be an issue uploading a Lookup table via the Sheets extension. Here is the response when uploading 
![image](https://github.com/mixpanel/sheets/assets/126842177/46e57fdc-5f5b-493f-8317-52083a361c61)

I tried to upload to this Lookup table: https://mixpanel.com/s/ODQTy
And I'm using a service account with Admin permissions. (crm-team.3800cc.mp-service-account) 
Here is a sample of the sheet I am trying to upload: https://docs.google.com/spreadsheets/d/1T_x3skmZ_x_Kba-PsukULAYatw9GY80DHYbp83iBCLE/edit?usp=sharing 

Testing on other projects, the upload works, so it seems like a project-specific bug. 

Thanks!

**Comment by dorothy-koh** [comment]
Is it possible to notify janice.teo@zalora.com if there's any updates? thanks!

**Comment by ak--47** [comment]
we can't seem to reproduce, closing for now.
