### ISSUE TITLE
401 error when run 'mixpanel -> sheet'

### ISSUE THREAD

**Issue by kayamfitlab** [ak--47/sheets-mixpanel#19]
why this error occured and how can i resolve it?

thank you in advance.
![image](https://github.com/mixpanel/sheets/assets/145001439/36f4a3d3-85e9-44fa-bfc0-1d3eb3a55769)

**Comment by JakeWymer** [comment]
Hey @kayamfitlab, it looks like the service account you're attempting to authenticate with doesn't have permissions to authenticate with this project. To export from this project, you'll need to create a new service account from the project settings or organization settings. If you create it from the organization settings, be sure you select this project and any other projects you want to authorize from the projects dropdown.
 
Attaching an example below:
<img width="1180" alt="Screen Shot 2023-09-15 at 11 40 42 AM" src="https://github.com/mixpanel/sheets/assets/8817258/7fcd1eb1-0f91-4793-9915-12556f82c547">
