### ISSUE TITLE
Inquiry Regarding Mixpanel Integration with Google Sheets

### ISSUE THREAD

**Issue by MaryamShakir13** [ak--47/sheets-mixpanel#23]
We recently came across an intriguing option that facilitates the integration of Mixpanel with Google Sheets, allowing data to be populated between these two platforms. The integration link can be found here: (https://workspace.google.com/marketplace/app/sheets_%E2%87%94_mixpanel/1078767167468).

Before seeking approval from our company's InfoSec team, I would like to clarify two concerns:

1. **Data Security:** Could you confirm whether there is any possibility that Google Sheets may compromise our users' sensitive information available on Mixpanel? We want assurance that the integration is 100% secure.

2. **Effect on Existing API Usage**: We are currently utilizing the Event Export and Insight Export APIs from Mixpanel to integrate with different platforms. Will the integration between Sheets and Mixpanel have any impact on our current API usage? Specifically, will it affect the rate limits mentioned in the raw event export API documentation: [https://developer.mixpanel.com/reference/raw-event-export]

Your prompt response to these concerns would greatly assist us in making an informed decision regarding the integration.

**Note:** Already raised this concern to mixpanel support and the team diverted me towards GitHub platform.

We look forward to your guidance on this matter.

**Comment by ak--47** [comment]
hi @MaryamShakir13 ... sorry for the delay!

- the extension is secure, and you may review the source code (it's open source). it runs as a google add-on inside the container... so it is completely sandboxed inside your browser's session with google. nothing is actually installed on your browser. the private data (like your tokens / keys) are stored inside of google's [document properties service](https://developers.google.com/apps-script/reference/properties/properties-service#getDocumentProperties()) which is only accessible by users authorized to access the sheet

- yes, the extension will effect your existing API usage. if you run a sync every hour, it will count as one request on that hour.
