### ISSUE TITLE
Not Able to Authenticate

### ISSUE THREAD

**Issue by nitin786pandey** [ak--47/sheets-mixpanel#24]
I tried using it , But I am not able to authenticate somehow. 

![image](https://github.com/mixpanel/sheets/assets/78100074/bb5b21bb-b102-4b9f-82dc-685fb70e0b3e)
 
Here is the Image
![Screenshot 2024-01-15 175344](https://github.com/mixpanel/sheets/assets/78100074/6f91f7c6-e463-4a08-aecd-8bf6eb06f4de)

**Comment by ak--47** [comment]
@nitin786pandey we see this issue when you are logged into multiple google accounts at the same time, and your sheets is owned by one account (personal) but you installed the extension on your other account (business)

see: https://github.com/mixpanel/sheets/issues/8#issuecomment-1546312057

are you able to try logging out and ensuring the extension is installed on the same account you're trying to use with your sheet?

thanks!

**Comment by ak--47** [comment]
cc @JakeWymer ... there's nothing we can do to prevent the multiple google account case, but perhaps  maybe update the error message to be more helpful, like `Your current google account does not have permission to use this; ensure you have installed mp-sheets on your current google account` ... 

context: https://groups.google.com/g/google-analytics-spreadsheet-add-on/c/sarnUsi3KdI

**Comment by nitin786pandey** [comment]
Hey , your advice really worked. I tried sheets in incognito mode , it
synced well. I am really too happy to use this feature. I connected
bigquery to sheets
