### ISSUE TITLE
Sync failing with "too many time-based triggers in this document" message

### ISSUE THREAD

**Issue by kochajkiewicz** [ak--47/sheets-mixpanel#25]
Clicking "run" – one-time sync works well.

Clicking "sync" results in the following message:

> Exception: This add-on has created too many time-based triggers in this document for this Google user account

I changed service accounts in that particular spreadsheet settings before trying to switch on sync again.

**Comment by ak--47** [comment]
@kochajkiewicz thanks for writing in. this message occurs when too many syncs have been scheduled for single sheet...

if you go here:
https://script.google.com/u/1/home/triggers

do you see a long list of triggers? (time based) if so, you may have to delete some of them.

a user may only have 30 triggers associated with a google account.

for the sheets extension, i would try pressing the delete button in the UI; this clears out any syncs associated with the document. as a last resort, you can uninstall and reinstall the extension. 

closing for now, but reopen if you are still blocked.
