### ISSUE TITLE
No Sync Option

### ISSUE THREAD

**Issue by pbtaffi** [ak--47/sheets-mixpanel#26]
Hi,

The import once (run) worked as expected when connected to my google workspace but there is no sync option.
I need to sync the google sheet to my mixpanel account periodically. I'm on a paid plan of mixpanel.

![Screenshot 2024-03-04 at 12 05 16](https://github.com/mixpanel/sheets/assets/95842625/c19bbd4a-b7bc-4fe0-843c-1f52ee82e435)

Please help.
Thank you.

**Comment by ak--47** [comment]
@fashionado 

events are immutable, so syncs are not support for events. 

you can sync profiles + groups, but not events.

**Comment by pbtaffi** [comment]
ok @ak--47 . Is there a way for me to periodically push newly added rows from a google sheet to mixpanel  whenever google sheet is updated ?

I do see a sync option under the extension menu. If I click on it, will it sync only the new data or will create duplicate events for the old data too ?
![Screenshot 2024-03-04 at 17 57 10](https://github.com/mixpanel/sheets/assets/95842625/1198314d-ce2e-41d6-95ab-2ace2c731c58)


Thank you.

**Comment by ak--47** [comment]
@fashionado it will not created duplicate events provided you give an $insert_id with your data (which is like a row identifier)

https://developer.mixpanel.com/reference/import-events#propertiesinsert_id
