### ISSUE TITLE
Didn't work for me

### ISSUE THREAD

**Issue by dasilvacontin** [ak--47/sheets-mixpanel#7]
I tried importing this:

event name | distinct_id | timestamp
-- | -- | --
Event Test | david.dasilvacontin@emitwise.com | 11 May 2023 13:57

It says that it succeeds:

<img width="636" alt="image" src="https://github.com/mixpanel/sheets/assets/1260830/7fe5f45f-319c-45e0-bbdb-372c8df2017b">

But it does not appear on the app:

<img width="1320" alt="image" src="https://github.com/mixpanel/sheets/assets/1260830/3834758a-86c7-4379-8427-1067c631a570">

Any help is appreciated :)

**Comment by dasilvacontin** [comment]
I have tried with both "api secret" and "service account" details. Both said "success", but I still can't see the events in the account.

**Comment by ak--47** [comment]
@dasilvacontin have you tried searching by your distinct_id? (all events where distinct_id = david@) 

sometimes in can take a bit for the drop-downs to populate; if you provide your mixpanel project id, we can take a look at the project and see what might be happening. thanks!

**Comment by dasilvacontin** [comment]
I tried searching by the event name. I've now tried by the distinct_id, and it didn't work either. (I _am_ able to see other events we have for the same distinct_id).

The project ID is 2094745. Thank you lots for the help, @ak--47 ! :)

**Comment by dasilvacontin** [comment]
I found the reason it was not working: https://github.com/mixpanel/sheets/issues/10.
