### ISSUE TITLE
Authorization didn't work despite entering valid service account details

### ISSUE THREAD

**Issue by mariaubergine** [ak--47/sheets-mixpanel#8]
<img width="301" alt="Screenshot 2023-05-12 at 9 41 06 AM" src="https://github.com/mixpanel/sheets/assets/66301989/1681a2e9-6aac-4047-a20b-129608ddc39b">

Hi there, 

The RUN didn't work for me despite valid service account details (username + secret) with `admin` privileges. I've tried a few service account details. I'm using the Mixpanel -> Sheets functionality. 

Would appreciate any support here! Thank you.

**Comment by ak--47** [comment]
hey @mariaubergine we see this issue when you are logged into multiple google accounts in the same window and one google account has the extension installed while another owns the sheet. 

can you try logging out of all google accounts and make sure the sheet is owned by the same google account in which you installed the extension? let us know if that works! thanks!

**Comment by mariaubergine** [comment]
Thanks @ak--47 -- this worked, thanks!

**Comment by ak--47** [comment]
@mariaubergine thanks for confirming... in a future version, we'll try to provide a more helpful error message. i'll leave this open for now so we can track progress!
