### ISSUE TITLE
Is project ID validation working?

### ISSUE THREAD

**Issue by dasilvacontin** [ak--47/sheets-mixpanel#9]
I tried running the import adding an extra character to the project ID, to see if it failed. But to my surprise, it didn't fail.

**Comment by dasilvacontin** [comment]
You can write anything on the project token, and it will not fail.

**Comment by ak--47** [comment]
hi @dasilvacontin thanks for writing in.

tokens are not used for events; just for user profiles + group profiles. project Ids are only necessary when using service accounts (not API secrets). 

ideally the UI would only ask for what it needs, but we wanted to keep the form standard. will take that into consideration for future releases.
